INSERT INTO questions (month, day, question) VALUES
(0, 1, 'Love is...'),
(0, 2, 'Make a New Year''s resolution.'),
(0, 3, 'What feels vitally important right now?'),
(0, 4, 'Who inspires you?'),
(0, 5, 'When''s the last time your partner made you laugh out loud?'),
(0, 6, 'Today was surprising because...'),
(0, 7, 'What is your Achilles heel?'),
(0, 8, 'What are you ready to release?'),
(0, 9, 'If I had to describe you in a single word, it would be...'),
(0, 10, 'What''s worth celebrating today?'),
(0, 11, 'Describe the last meal you enjoyed together.'),
(0, 12, 'Id be completely shocked if you...'),
(0, 13, 'Which famous couple would you like to double-date?'),
(0, 14, 'Jot down one positive change you''ve already made this year.'),
(0, 15, 'What irritates you?'),
(0, 16, 'Write down the kindest thing your partner has said to you lately.'),
(0, 17, 'What are your top three wishes?'),
(0, 18, 'I love it when you wear...'),
(0, 19, 'What''s your weekday-morning ritual?'),
(0, 20, 'Out of the two of you who''s feeling more optimistic today?'),
(0, 21, 'Can you remember the last time your partner appeared in a dream?'),
(0, 22, 'Coffee, juice, tea, or...'),
(0, 23, 'In a hundred years, how would you like to be remembered?'),
(0, 24, 'If you started a company together, what would it be?'),
(0, 25, 'If you were to make a playlist for your partner, what would the title be?'),
(0, 26, 'Who feels more secure at work right now: you or your partner?'),
(0, 27, 'What''s the nicest compliment you''ve received lately?'),
(0, 28, 'Which celebrity would you like to invite over for the weekend?'),
(0, 29, 'Being with you feels like...'),
(0, 30, 'What would you like to master?'),
(0, 31, 'If you could give your partner a superpower, what would it be?')
;
